### ISSUE TITLE
Module does not work in react

### ISSUE THREAD

**Issue by OR13** [bpmn-io/bpmn-auto-layout#22]
__Describe the Bug__

installing latest versions and trying the example in the readme leads to  

```
AutoLayout.js:15 Uncaught (in promise) TypeError: BpmnModdle is not a constructor
```
its caused by:

```
function AutoLayout() {
  this.moddle = new BpmnModdle(); // the import for this not right / default export needs to be updated 
  this.DiFactory = new DiFactory(this.moddle);
  this.nodeCount = -1;
}
```

__Steps to Reproduce__

See above.

__Expected Behavior__

Expect the layout to work with the latest versions of `bpmn-moddle`.

__Environment__

- Host (Browser/Node version), if applicable: Tested in node... it sorta works... tested in the browser it does not work
- OS: macOS
- Library version:

```
   "bpmn-auto-layout": "^0.1.0",
    "bpmn-engine": "^13.0.0",
    "bpmn-js": "^8.9.0",
    "bpmn-moddle": "^7.1.2",
```

**Comment by OR13** [comment]
Is there a recommended alternative to this library that is maintained?

**Comment by philippfromme** [comment]
There is no alternative solution that is maintained by the bpmn.io team, sorry. 😢

**Comment by OR13** [comment]
@ermarkar You pretty much need to use other software to fix the layout manually... see also https://github.com/process-analytics/bpmn-visualization-js/issues/1837

**Comment by goto-loop** [comment]
I'm having the same issue with the latest version and was able to fix it with the changes in https://github.com/bpmn-io/bpmn-auto-layout/pull/31/files.

@corocoto You've decided to close the pull request, but I don't quite understand why. Were you able to solve the issue in a different way?

**Comment by goto-loop** [comment]
I agree that rewriting all code using a consistent style would be nicer than fixing things here and there. However, with the project not being officially maintained, it seems unlikely that this will happen in the near future. So in my opinion it would make sense to fix these kind of "breaking" issues.

Just for context: In order to use the package with React _at all_, you need to clone it, modify the code, build it and then install from your local copy. It's so much effort for a problem that you, @corocoto, have already solved.

@nikku It would be great to hear your opinion on this.

**Comment by OR13** [comment]
auto layout is really useful if you are compiling to BPMN from another data source.

**Comment by nikku** [comment]
Should start to work with https://github.com/bpmn-io/bpmn-auto-layout/pull/33 being merged.
